// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUoxXx16F0HT3SbLrANyw9ATR7KjRFLE8',
    appId: '1:13479209665:web:506302fdb4677725128240',
    messagingSenderId: '13479209665',
    projectId: 'movieshut-41be4',
    authDomain: 'movieshut-41be4.firebaseapp.com',
    storageBucket: 'movieshut-41be4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojGH87umWSa7XulWx23MCJnjA4_WAidw',
    appId: '1:13479209665:android:bbd96742fe46a5da128240',
    messagingSenderId: '13479209665',
    projectId: 'movieshut-41be4',
    storageBucket: 'movieshut-41be4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQdoZtUTisLApjLxb917V8nhG3UQtMv90',
    appId: '1:13479209665:ios:5098f01b38ff61f8128240',
    messagingSenderId: '13479209665',
    projectId: 'movieshut-41be4',
    storageBucket: 'movieshut-41be4.appspot.com',
    iosClientId:
        '13479209665-9jlpdpoklsd19164rqct3lv8lsqn37ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieshut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQdoZtUTisLApjLxb917V8nhG3UQtMv90',
    appId: '1:13479209665:ios:5098f01b38ff61f8128240',
    messagingSenderId: '13479209665',
    projectId: 'movieshut-41be4',
    storageBucket: 'movieshut-41be4.appspot.com',
    iosClientId:
        '13479209665-9jlpdpoklsd19164rqct3lv8lsqn37ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieshut',
  );
}
